Add restarting
GryphonRacingFSAE/Discord-Bot pull request #21
Opened 2023-08-17 19:54 UTC by DannyLeWasTaken

- Simply add /restart which will shutdown the bot, but thanks to the docker setup should in theory start back up.

2023-08-17 20:05 UTC, Nomalah requested changes
Put a short description of the command in the readme.
If you haven't already, it would be nice if you would install docker, run it locally using the command in the deploy job in the workflow, and then check if it works. Otherwise we'll just yolo it

2023-08-17 20:05 UTC, Nomalah commented on src/commands/restart.ts
> +
Typo

2023-08-17 20:15 UTC, DannyLeWasTaken commented
Tried to get docker up and running but it really doesn't like my PC.

2023-08-18 17:38 UTC, Nomalah approved these changes
Put a short description of the command in the readme.

2023-08-18 17:57 UTC, merged