Clean up + autodeploy
GryphonRacingFSAE/Discord-Bot pull request #5
Opened 2023-08-04 05:13 UTC by Nomalah

# Clean up + Autodeploy

Clean up the repo a little bit, add autodeploy

## Changes

- Adapted workflow to encompass deployment
- Changed files from .mts to .ts
- Changed imports from "*" to "node:*" if approprate
- Fixed style guide issues where found

## Deployment

- Created a dockerfile & container for the bot to run within

## Proof of functionality (screenshot, logs, etc)

Success in github actions workflow:
![image](https://github.com/GryphonRacingFSAE/Discord-Bot/assets/36043275/0b7c5fb9-6ed1-408e-943b-0d1949b5217b)

Bot is successfully hosted:
![image](https://github.com/GryphonRacingFSAE/Discord-Bot/assets/36043275/4906112a-461a-46a0-afc0-4bfd73b960e8

## Additional Notes

- Added a bunch of docs

## Checklist

- [x] Your code builds clean without any errors or warnings
- [x] Code has been formatted (clang-format, cmake-format, black, prettier, rustfmt, etc)
- [N/A] Where possible, unit tests have been added
- [x] Code is well-commented & understood

2023-08-05 10:06 UTC, DannyLeWasTaken commented
LGTM

2023-08-05 10:06 UTC, DannyLeWasTaken approved these changes

2023-08-06 01:33 UTC, notevanrutten requested changes
I'll assume all looks good considering I haven't worked with docker much. Just have a few changes for consistency in the readme (because OCD).

2023-08-06 01:33 UTC, notevanrutten commented on README.md
> +- Monitor and backup Audit logs (locally and on the server itself)
```suggestion
- Monitor and backup audit logs (locally and on the server itself)
```
why capital?

2023-08-06 01:33 UTC, notevanrutten commented on README.md
> +- Monitor our shop and send/update on whether the shop is open/closed (WIP)
```suggestion
- Monitor our shop door(s) and update on whether the shop is open/closed (WIP)
```

2023-08-06 01:33 UTC, notevanrutten commented on README.md
> +- Semi-automatic verification of members in discord (WIP)
```suggestion
- Semi-automatic verification of members in the Discord server (WIP)
```

2023-08-06 01:33 UTC, notevanrutten commented on README.md
> +We have an ESP32 at the main shop entrance monitoring if it's open or closed, if the status changes, it sends a POST request to a http server with the discord bot, which then sends a message to the D
```suggestion
We have an ESP32 at the main shop entrance monitoring if it's open or closed, if the status changes, it sends a POST request to an HTTP server with the Discord bot, which then sends a message to the server
```

2023-08-06 01:33 UTC, notevanrutten commented on README.md
> +Fetch latest team roster + payment status from onedrive (TBD how), verify email, verify student number, verify student ID? If passing all requirements, the user is given the role "verified".
```suggestion
Fetch latest team roster + payment status from OneDrive (TBD how), verify email, verify student number, verify student ID? If passing all requirements, the user is given the role "Verified".
```

2023-08-06 01:33 UTC, notevanrutten commented on README.md
> +node dist/index.mjs # Run Discord bot:
```suggestion
node dist/deploy-commands.js # Register any new slash commands (if applicable)
node dist/index.mjs # Run Discord bot
```

2023-08-06 01:33 UTC, notevanrutten commented on README.md
> +Initiate a countdown from a captain or lead, update the countdown every 5 minutes, and push it to the latest in the chat every day. Save countdowns locally to preserve countdowns between launches
```suggestion
Initiate a countdown from a Captain or Lead, update the countdown every 5 minutes, and push it to the latest in the chat every day. Save countdowns locally to preserve countdowns between launches.
```

2023-08-06 01:33 UTC, notevanrutten commented on README.md
> +Download the audit logs every week for the past week, and upload them to discord to the audit-logs channel (hidden by default). Can also be uploaded manually via command by Captains and Leads.
```suggestion
Download the audit logs every week for the past week, and upload them to Discord to the audit-logs channel (hidden by default). Can also be uploaded manually via command by Captains and Leads.
```

2023-08-06 01:33 UTC, notevanrutten commented on README.md
> +This bot is run on the Embedded subsection's shop computer, it's run in a docker container and locally saved files are mounted onto the filesystem so we can use them non-volatility.
```suggestion
This bot is run on the Embedded subsection's shop computer, it's run in a docker container and locally saved files are mounted onto the filesystem to ensure non-volatility.
```

2023-08-06 03:02 UTC, notevanrutten approved these changes
LGTM 👍

2023-08-06 03:04 UTC, merged