Fix countdown command referencing the wrong file
GryphonRacingFSAE/Discord-Bot pull request #7
Opened 2023-08-08 02:30 UTC by DannyLeWasTaken

# TASK TITLE

Countdown may refer to the wrong file and thus get confused which countdowns are where

## Changes

- Use resource/messages.json
- **This does introduce a breaking change and all ./messages.json should be deleted/moved to ./resources/messages.json**

2023-08-08 03:16 UTC, Nomalah requested changes
What happens if the file doesn't exist?

2023-08-08 13:40 UTC, DannyLeWasTaken commented
It will just create a new blank one I believe

2023-08-08 15:31 UTC, Nomalah commented
Test it, fs.readFileSync doesn't create a file if it doesn't exist, and if it did, JSON.parse would fail because of no content.

2023-08-09 02:18 UTC, Nomalah approved these changes

2023-08-09 02:18 UTC, merged